AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VPCParam:
    Type: String
    Default: 10.16.0.0/16
  SubnetParam:
    Type: String
    Default: 10.16.0.0/24
  NumSubnetsParam:
    Type: Number
    Default: 2
  SubnetLenParam:
    Type: Number
    Default: 8

Resources:
  myvpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        !Ref VPCParam
  mysubnet:
      Type: AWS::EC2::Subnet
      Properties:
        VpcId:
          Ref: myvpc
        CidrBlock:
          !Select [
            0,
            !Cidr [!Ref VPCParam, !Ref NumSubnetsParam, !Ref SubnetLenParam]]


